### ISSUE TITLE
Server error '502 Bad Gateway' for url 'http://127.0.0.1:11434/api/chat'

### ISSUE THREAD

**Issue by RussellXY** [jmorganca/ollama-python#14]
I'm sure the ollama service is running with this command: `ollama serve`. but I still got this when run the sample code:

![截屏2024-01-18 21 53 11](https://github.com/jmorganca/ollama-python/assets/8545620/5ec8ad93-e1e4-45d8-8701-139dc8a2b903)

```
Exception has occurred: ResponseError
Server error '502 Bad Gateway' for url 'http://127.0.0.1:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'http://127.0.0.1:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

During handling of the above exception, another exception occurred:

  File "/Users/xiongyu/Documents/python_project/youtube_translator/optimize.py", line 11, in <module>
    for part in ollama.chat('llama2:13b', messages=messages, stream=True):
ollama._types.ResponseError: 
```

**Comment by mxyng** [comment]
Where is your ollama service running? If it's not locally on port 11434, you'll need to change it by setting the `OLLAMA_HOST` environment variable or creating a custom client `ollama.Client(base_url='...').chat(...)`

**Comment by RussellXY** [comment]
I'm sure it's running locally on port 11434. because I run this command below in the terminal and ollama works well.

```
curl http://127.0.0.1:11434/api/chat -d '{
  "model": "llama2:13b",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```
but it fails when I run the python code on VSCode.

python code:
```
import ollama 


messages = [
  {
    'role': 'user',
    'content': 'Why is the sky blue?',
  },
]

for part in ollama.chat('llama2:13b', messages=messages, stream=True):
  print(part['message']['content'], end='', flush=True)

# end with a newline
print()
```

**Comment by RussellXY** [comment]
> Where is your ollama service running? If it's not locally on port 11434, you'll need to change it by setting the `OLLAMA_HOST` environment variable or creating a custom client `ollama.Client(base_url='...').chat(...)`

I'm sure it's running locally on port 11434. because I run this command below in the terminal and ollama works well.

```
curl http://127.0.0.1:11434/api/chat -d '{
  "model": "llama2:13b",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```
but it fails when I run the python code on VSCode.

python code:
```
import ollama 


messages = [
  {
    'role': 'user',
    'content': 'Why is the sky blue?',
  },
]

for part in ollama.chat('llama2:13b', messages=messages, stream=True):
  print(part['message']['content'], end='', flush=True)

# end with a newline
print()
```
